# Generated by Django 4.0.1 on 2022-03-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=400)),
                ('city', models.TextField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('form_btn', models.BooleanField()),
            ],
        ),
    ]
