# Generated by Django 4.0.1 on 2022-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('from', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=400)),
                ('city', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='FormModals',
        ),
    ]
